# Video-1:

## Introduction to Python
- Numbers
- Strings
- Lists
- Dictionaries
- Conditionals (if-else)
- Loops

### Integers and Float (decimals)

In [3]:
a=10
b=6
print(a+b,a-b,a*b,a/b)

16 4 60 1.6666666666666667


In [4]:
a=10.1
b=6.4
print(a+b,a-b,a*b,a/b)

16.5 3.6999999999999993 64.64 1.5781249999999998


In [5]:
a=2
print(type(a))
print(a[0])
print(a[1])
print(a[2])
type(a)

<class 'int'>


TypeError: 'int' object is not subscriptable

In [9]:
a=2.5
print(type(a))

<class 'float'>


In [10]:
print(a[0])
print(a[1])
print(a[2])

TypeError: 'float' object is not subscriptable

### Strings

In [7]:
a='2.5'
print(type(a))
print(a[0])
print(a[1])
print(a[2])
type(a)

<class 'str'>
2
.
5


str

In [18]:
a='Banana'
b='Shake'

In [19]:
c=a+b
print(c)

BananaShake


In [20]:
d=a+" "+b  #Let us add a space bar too
print(d)

Banana Shake


In [14]:
print(len(a))

6


In [22]:
print(c[2])

n


In [24]:
print(c[2:8])  #sustring :all chars between 2nd and 8-1 th chr
print(d[2:8])

nanaSh
nana S


In [16]:
print(c[89])

IndexError: string index out of range

In [17]:
print(c[-1])

e


### Lists
Let us create a shooping list:
    1. Milk
    2. Banana
    3. Carrots

In [23]:
a=['Milk','Banana','Carrot'] #list-1
print(a)
print(len(a))
print(a[2])
a[2]='Tomato'  #list modification
print(a)
b=['Rice','Sugar','Salt'] #list-2
print(b)
d=a+b       #concatenation of two lists
print(a+b) 
print(d)
e=d+['Apple']  #add another item "Apple"
print(e)


['Milk', 'Banana', 'Carrot']
3
Carrot
['Milk', 'Banana', 'Tomato']
['Rice', 'Sugar', 'Salt']
['Milk', 'Banana', 'Tomato', 'Rice', 'Sugar', 'Salt']
['Milk', 'Banana', 'Tomato', 'Rice', 'Sugar', 'Salt']
['Milk', 'Banana', 'Tomato', 'Rice', 'Sugar', 'Salt', 'Apple']


In [26]:
#list can contain many datatypes
a=[1,2,'tyr']
print(a)
print(type(a))
b=[23,45,'hyu']
print(b)
print(type(b))
c=a+b     #concatenation
print(c)
print(type(c))
print(a[2])  #indexing
print(c[4])

[1, 2, 'tyr']
<class 'list'>
[23, 45, 'hyu']
<class 'list'>
[1, 2, 'tyr', 23, 45, 'hyu']
<class 'list'>
tyr
45


In [27]:
a[2]='fg'
print(a)

[1, 2, 'fg']


### Dictionaries
How to add quantities to your list:
    1. Milk: 1 litre
    2. Banana: 12
    3. Carrot: 5    

In [28]:
a={"Milk":"1 litre","Sugar":"1 kg","Paneer":"500 gms","Cake":1}
print(a)
print(type(a))
print(len(a))
print(a["Paneer"]) #what is the quantity of Paneer
a["Cake"]=2  #dictionary modification
print(a["Cake"])
print(a)
#add 1 kg apple
a["Apple"]="1 kg"
print(a)

{'Milk': '1 litre', 'Sugar': '1 kg', 'Paneer': '500 gms', 'Cake': 1}
<class 'dict'>
4
500 gms
2
{'Milk': '1 litre', 'Sugar': '1 kg', 'Paneer': '500 gms', 'Cake': 2}
{'Milk': '1 litre', 'Sugar': '1 kg', 'Paneer': '500 gms', 'Cake': 2, 'Apple': '1 kg'}


In [29]:
print(a.keys())  #both returs output as lists
print(a.values())

dict_keys(['Milk', 'Sugar', 'Paneer', 'Cake', 'Apple'])
dict_values(['1 litre', '1 kg', '500 gms', 2, '1 kg'])


### Conditionals
If, elif, else

In [42]:
i=4
if i<0:
    print("Negative")
elif i==0:
    print("Neutral")
else:
    print("Positive")

Positive


In [49]:
#add 5 bananas in the dictionary a, if a["Banana"]=5 iswritten, always overwrite over initial value, 
#if key is present increase itsvalue by 5, else add key with given amount

if "Banana" in a:
    a["Banana"]=a["Banana"]+5
else:
    a["Banana"]=5
    
print(a) 



if "Cake" in a:
    a["Cake"]=a["Cake"]+5
else:
    a["Cake"]=5
    
print(a)    


{'Milk': '1 litre', 'Sugar': '1 kg', 'Paneer': '500 gms', 'Cake': 2, 'Apple': '1 kg', 'Banana': 5}
{'Milk': '1 litre', 'Sugar': '1 kg', 'Paneer': '500 gms', 'Cake': 7, 'Apple': '1 kg', 'Banana': 5}


### Loops
#### For Loop

In [30]:
range(5)   

range(0, 5)

In [31]:
for i in range(5):  
    print(i)

0
1
2
3
4


In [54]:
for key in a:
    print(key,"-",a[key])  #prints all the items in the list along with their quantities
    
print("\n")    
for key in a:
    print(key,"-",a[key],end='')  #end parameter
    
print("\n")   
for key in a:
    print(key,"-",a[key],sep='')  #sep parameter

Milk - 1 litre
Sugar - 1 kg
Paneer - 500 gms
Cake - 7
Apple - 1 kg
Banana - 5


Milk - 1 litreSugar - 1 kgPaneer - 500 gmsCake - 7Apple - 1 kgBanana - 5

Milk-1 litre
Sugar-1 kg
Paneer-500 gms
Cake-7
Apple-1 kg
Banana-5


#### While Loop
When we don't know where to end, then use while loop. Here termination condition is used.

In [56]:
#list all the integers starting from 0, such that the sum of their squares is less than 20
i=0
sum_of_squares=0
while sum_of_squares<=20:
    print(i)
    i+=1
    sum_of_squares=sum_of_squares+(i*i)

0
1
2
3


# Video-2:
### Functions
input -> F -> output

In [32]:
def myprint(x):
    print(x)

In [33]:
x=2
myprint(x)

2


In [59]:
def myprint(x):
    if x%2==0:
        print(x,"is even.")
    else:
        print(x,"is odd.")
        
        
myprint(7)
myprint(70)
myprint(6)
myprint(8)

    

7 is odd.
70 is even.
6 is even.
8 is even.


In [34]:
def findlarger_1(x,y):
    if x>y:
        max=x
    else:
        max=y
    return max    

print(findlarger_1(5,6))
findlarger_1(5,6)

6


6

In [37]:
def findlarger_2(x,y):
    max=x
    if x<y:
        max=y
    return max    

print(findlarger_2(5.77,5.78))
findlarger_2(5.77,5.78)

5.78


5.78

In [41]:
def evenodd(x):
    if x%2==0:            #can write (x%2==0)
        print("even")
    else:
        print("odd")
    x+=2    
    return x+2    #call by value

y=9
print(y)
print(evenodd(y))

print(y)

9
odd
13


In [71]:
def addItem(a,key,val=1):
    if key in a:
        a[key]=a[key]+val
    else:
        a[key]=val
    print(a)
    return a

a={"Apple":2,"Banana":4}
print(a)
addItem(a,"Apple",5)
addItem(a,"Guava",6)
addItem(a,"Guava") #if val isnot given by default it takes 1
print(a)  #call by reference

{'Apple': 2, 'Banana': 4}
{'Apple': 7, 'Banana': 4}
{'Apple': 7, 'Banana': 4, 'Guava': 6}
{'Apple': 7, 'Banana': 4, 'Guava': 7}
{'Apple': 7, 'Banana': 4, 'Guava': 7}


## Classes
A structure containing varoiables and functions.
Ex. Create a Shopping List class that can add and subtract items and their quantities

In [2]:
class ShoppingList:
    def __init__ (self):
        self.listdict={}  #empty list is created
        
    def addItem(self,key,val):
        if key in self.listdict:
            self.listdict[key]=self.listdict[key]+val
        else:
            self.listdict[key]=val
    
    def subtractItem(self,key,val):
        if key in self.listdict:
            self.listdict[key]=self.listdict[key]-val
            
    def removeItem(self,key):
        if key in self.listdict:
            del(self.listdict[key])
            
    def printList(self):
        print(self.listdict)
        
        
        
# there can be one ShoppoingList for fruits, another ShppingList class for clothes, another for accessories.....        

In [3]:
sl1=ShoppingList()
sl1.addItem("Banana",12)
sl1.addItem("Apple",34)
sl1.printList()
sl1.subtractItem("Banana",2)
sl1.printList()
sl1.removeItem("Apple")
sl1.printList()
sl1.subtractItem("Guava",2)
sl1.printList()

{'Banana': 12, 'Apple': 34}
{'Banana': 10, 'Apple': 34}
{'Banana': 10}
{'Banana': 10}


In [84]:
sl2=ShoppingList()
sl2.printList()
sl2.addItem("notebook",4)
sl2.addItem("copy",5)
sl2.printList()
sl2.addItem("pen",8)
sl2.printList()
sl2.removeItem("pen")
sl2.subtractItem("copy",1)
sl2.printList()

{}
{'notebook': 4, 'copy': 5}
{'notebook': 4, 'copy': 5, 'pen': 8}
{'notebook': 4, 'copy': 4}


sl1 and sl2 are two instances of the class ShoppingList

## Matrix Multiplication

### Numpy
Matrix Manipulation
- Initializing matrix
- Random matrix
- Matrix Addition, Multiplication and Concatenation

In [43]:
import numpy as np

A = np.ones((3,2))
print(A)

B = np.zeros((3,2))
print(B)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [44]:
C = np.eye(3)
print(C)

D = np.diag([3,2,5])
print(D)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[3 0 0]
 [0 2 0]
 [0 0 5]]


In [45]:
E = np.random.random((3,2))
print(E)

print(E.T)  #transpose of E

[[0.66994999 0.66468546]
 [0.02275006 0.42889688]
 [0.87119657 0.681676  ]]
[[0.66994999 0.02275006 0.87119657]
 [0.66468546 0.42889688 0.681676  ]]


In [46]:
#different ways of accessing individual elements

print(E, '\n')

print(E[0,0])
print(E[1,0])
print(E[-1,-1])
print(E[0,:])
print(E[:,1])

[[0.66994999 0.66468546]
 [0.02275006 0.42889688]
 [0.87119657 0.681676  ]] 

0.6699499901219405
0.022750063309087243
0.681675997407601
[0.66994999 0.66468546]
[0.66468546 0.42889688 0.681676  ]


### Matrix Addition
C= A^T+2B

In [6]:
A = np.ones((2,3))
B = np.random.random((3,2))
C = A.T+2*B

print(A)
print(B)
print(2*B)  #element wise product
print(C)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[[1. 1. 1.]
 [1. 1. 1.]]
[[0.10832506 0.31056528]
 [0.47837545 0.74059354]
 [0.03234645 0.51680465]]
[[0.21665012 0.62113056]
 [0.95675091 1.48118707]
 [0.06469289 1.03360931]]
[[1.21665012 1.62113056]
 [1.95675091 2.48118707]
 [1.06469289 2.03360931]]


### Matrix Manipulation
C= AB

In [48]:
C = A.dot(B)  #dot product
print(C)

[[1.61929846 0.71431525]
 [1.61929846 0.71431525]]


In [49]:
C = A.T*B
print(C)

[[0.3189272  0.025808  ]
 [0.96044087 0.35493553]
 [0.33993039 0.33357172]]


In [20]:
A=np.array([[1, 2],
            [1, 2]])

B=np.array([[2, 3],
            [1, 2]])

print(A)
print("\n")
print(B)
print("\n")
print(A*B)  #element wise
print("\n")
print(A.dot(B))  #normal matrix product
print("\n")
print(2*B)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[[1 2]
 [1 2]]


[[2 3]
 [1 2]]


[[2 6]
 [1 4]]


[[4 7]
 [4 7]]


[[4 6]
 [2 4]]


### Matrix Concatenation
C = [A^T B]

In [21]:
print(A.T.shape, B.shape)
C = np.concatenate((A.T,B), axis=1)  #axis=1 means column wise
D = np.concatenate((A.T,B), axis=0)   #axis=0 means row wise
print(C)
print(D)

(2, 2) (2, 2)


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[[1 1 2 3]
 [2 2 1 2]]
[[1 1]
 [2 2]
 [2 3]
 [1 2]]


In [22]:
# concatenating vectors
a = np.ones(4)
b = np.array([2,3,4,5])
print(a);print(b)
X = np.hstack([a,b])  #horizontally concatenate
Y = np.vstack([a,b])  #vertically concatenate
print(X)
print(Y)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[1. 1. 1. 1.]
[2 3 4 5]


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[1. 1. 1. 1. 2. 3. 4. 5.]
[[1. 1. 1. 1.]
 [2. 3. 4. 5.]]


In [27]:
T=np.array([[[1,2],
             [2,3],
             [3,4]],
            [[1,2],
             [2,3],
             [3,4]],
            [[1,2],
             [2,3],
             [3,4]]])

print(T)

<IPython.core.display.Javascript object>

[[[1 2]
  [2 3]
  [3 4]]

 [[1 2]
  [2 3]
  [3 4]]

 [[1 2]
  [2 3]
  [3 4]]]


In [28]:
T=np.array([[[1,2],
             [2,3],
             [3,4]],
            [[1,2],
             [2,3],
             [3,4]],
            [[1,2,4],
             [2,3,5],
             [3,4,5]]])

print(T)

<IPython.core.display.Javascript object>

[[list([1, 2]) list([2, 3]) list([3, 4])]
 [list([1, 2]) list([2, 3]) list([3, 4])]
 [list([1, 2, 4]) list([2, 3, 5]) list([3, 4, 5])]]


<ipython-input-28-be8d3709e1de>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  T=np.array([[[1,2],


In [29]:
T=np.array([[[1,2],
             [2,3],
             [3,4]],
            [[1,2],
             [2,3],
             [3,4]],
            [[1,2,4],
             [2,3,5],
             [3,4,5]]],dtype=object)

print(T)

<IPython.core.display.Javascript object>

[[list([1, 2]) list([2, 3]) list([3, 4])]
 [list([1, 2]) list([2, 3]) list([3, 4])]
 [list([1, 2, 4]) list([2, 3, 5]) list([3, 4, 5])]]


In [30]:
import math
x=4
print(math.exp(x))
print(math.log(x))
print(pow(x,2))

54.598150033144236
1.3862943611198906
16


In [56]:
math.log(-3)  #domain error

ValueError: math domain error

In [34]:
abs(3-7)  #absolute difference

4

In [35]:
from math import *
log(2)

0.6931471805599453

In [45]:
#perform sqrt() and exp() methods
import decimal
m=decimal.Decimal(25.1)
print(m)
print("sq:",m.sqrt())
print("e^x:"+str(m.exp()))
print(type(str(m.sqrt())))
print(type(m.sqrt()))

25.10000000000000142108547152020037174224853515625
sq: 5.009990019950139723140904128
e^x:79577720706.64344915418048685
<class 'str'>
<class 'decimal.Decimal'>
