In [3]:
!pip install keras

     ---------------------------------------- 0.0/48.7 kB ? eta -:--:--
     ------------------------- -------------- 30.7/48.7 kB 1.4 MB/s eta 0:00:01
     ---------------------------------------- 48.7/48.7 kB 1.2 MB/s eta 0:00:00
   ---------------------------------------- 0.0/1.2 MB ? eta -:--:--
   ------------- -------------------------- 0.4/1.2 MB 8.5 MB/s eta 0:00:01
   ----------------------------- ---------- 0.9/1.2 MB 9.2 MB/s eta 0:00:01
   -------------------------------------- - 1.1/1.2 MB 8.1 MB/s eta 0:00:01
   ---------------------------------------- 1.2/1.2 MB 7.6 MB/s eta 0:00:00
   ---------------------------------------- 0.0/133.7 kB ? eta -:--:--
   ---------------------------------------- 133.7/133.7 kB 8.2 MB/s eta 0:00:00
   ---------------------------------------- 0.0/213.2 kB ? eta -:--:--
   --------------------------------------- 213.2/213.2 kB 12.7 MB/s eta 0:00:00
   ---------------------------------------- 0.0/283.5 kB ? eta -:--:--
   -------------------

In [7]:
!pip install tensorflow

   ---------------------------------------- 0.0/385.2 MB ? eta -:--:--
   ---------------------------------------- 0.5/385.2 MB 10.2 MB/s eta 0:00:38
   ---------------------------------------- 0.9/385.2 MB 9.9 MB/s eta 0:00:39
   ---------------------------------------- 1.4/385.2 MB 9.9 MB/s eta 0:00:39
   ---------------------------------------- 1.9/385.2 MB 10.2 MB/s eta 0:00:38
   ---------------------------------------- 2.5/385.2 MB 10.5 MB/s eta 0:00:37
   ---------------------------------------- 3.0/385.2 MB 10.7 MB/s eta 0:00:36
   ---------------------------------------- 3.6/385.2 MB 10.9 MB/s eta 0:00:36
   ---------------------------------------- 4.1/385.2 MB 10.8 MB/s eta 0:00:36
   ---------------------------------------- 4.5/385.2 MB 10.6 MB/s eta 0:00:36
    --------------------------------------- 4.8/385.2 MB 10.3 MB/s eta 0:00:38
    --------------------------------------- 5.4/385.2 MB 10.4 MB/s eta 0:00:37
    --------------------------------------- 5.8/385.2 MB 10.2 

# Implementation of RNN

In [16]:
from keras import Sequential
from keras.layers import Dense, SimpleRNN

In [18]:
model = Sequential()

# nodes in hidden layer = 3
# maximum timestep = maximum length of input = 4
# number of total unique words = corpus size = 5 # feature size
model.add(SimpleRNN(3,input_shape=(4,5))) 
model.add(Dense(1, activation='sigmoid'))

model.summary()

C:\Users\koyel\anaconda3\Lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ simple_rnn_3 (SimpleRNN)             │ (None, 3)                   │              27 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │               4 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 31 (124.00 B)

 Trainable params: 31 (124.00 B)

 Non-trainable params: 0 (0.00 B)

In [20]:
print(dir(model))

['__call__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_add_trackable_child', '_add_variable_with_custom_getter', '_allow_non_tensor_positional_args', '_api_export_path', '_api_export_symbol_id', '_assert_compile_called', '_assert_input_compatibility', '_assign_variable_values', '_auto_config', '_build_by_run_for_kwargs', '_build_by_run_for_single_pos_arg', '_build_shapes_dict', '_call_has_mask_arg', '_call_has_training_arg', '_call_signature', '_called', '_check_quantize_args', '_check_super_called', '_checkpoint_adapter', '_checkpoint_dependencies', '_clear_losses', '_clear_previous_trainer_metrics', '_compile_loss', '_compile_metrics', '_compiled_metrics_update_state', 

In [22]:
model.get_weights()

[array([[-0.31493723,  0.7839305 ,  0.8132624 ],
        [-0.54321647, -0.5802344 , -0.85859287],
        [-0.28778887,  0.7616959 ,  0.36422175],
        [-0.48946092, -0.4440656 , -0.0024364 ],
        [ 0.4596191 , -0.27612025,  0.5997943 ]], dtype=float32),
 array([[-0.20821118, -0.97788864,  0.01953942],
        [ 0.9716158 , -0.20449936,  0.1189234 ],
        [-0.11229805,  0.04374599,  0.9927111 ]], dtype=float32),
 array([0., 0., 0.], dtype=float32),
 array([[ 1.0393664 ],
        [-0.46767992],
        [ 0.5251894 ]], dtype=float32),
 array([0.], dtype=float32)]

In [25]:
model.get_weights()[0].shape

(5, 3)

In [27]:
model.get_weights()[1].shape

(3, 3)

In [29]:
model.get_weights()[2].shape

(3,)

In [31]:
model.get_weights()[3].shape

(3, 1)

In [33]:
model.get_weights()[4].shape

(1,)

# Sentiment Anlysis Using RNN - Integer Encoding

In [2]:
# to vectorize input text data : integer encoding, Embeddings
import numpy as np

In [73]:
docs = ['go india',
       'india india',
       'hip hip hurray',
       'jeetega bhai jeetega india jeetega',
       'bharat mata ki jai',
       'kohli kohli',
       'sachin sachin',
       'dhoni dhoni', 
       'modi ji ki jai', 
       'inquilab jindabad'
       ]

In [75]:
# import tensorflow as tf
# integer encoding - Is this same as LabelEncoding?
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token = '<nothing>')

In [77]:
tokenizer.fit_on_texts(docs)

In [79]:
tokenizer.word_index

{'<nothing>': 1,
 'india': 2,
 'jeetega': 3,
 'hip': 4,
 'ki': 5,
 'jai': 6,
 'kohli': 7,
 'sachin': 8,
 'dhoni': 9,
 'go': 10,
 'hurray': 11,
 'bhai': 12,
 'bharat': 13,
 'mata': 14,
 'modi': 15,
 'ji': 16,
 'inquilab': 17,
 'jindabad': 18}

In [81]:
tokenizer.word_counts

OrderedDict([('go', 1),
             ('india', 4),
             ('hip', 2),
             ('hurray', 1),
             ('jeetega', 3),
             ('bhai', 1),
             ('bharat', 1),
             ('mata', 1),
             ('ki', 2),
             ('jai', 2),
             ('kohli', 2),
             ('sachin', 2),
             ('dhoni', 2),
             ('modi', 1),
             ('ji', 1),
             ('inquilab', 1),
             ('jindabad', 1)])

In [83]:
tokenizer.document_count # number of rows

10

In [85]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[10, 2],
 [2, 2],
 [4, 4, 11],
 [3, 12, 3, 2, 3],
 [13, 14, 5, 6],
 [7, 7],
 [8, 8],
 [9, 9],
 [15, 16, 5, 6],
 [17, 18]]

In [87]:
# as inputs are of varying size - pad them to get inputs of same size
from keras.utils import pad_sequences

In [89]:
sequences = pad_sequences(sequences, padding='post')
sequences

array([[10,  2,  0,  0,  0],
       [ 2,  2,  0,  0,  0],
       [ 4,  4, 11,  0,  0],
       [ 3, 12,  3,  2,  3],
       [13, 14,  5,  6,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [ 9,  9,  0,  0,  0],
       [15, 16,  5,  6,  0],
       [17, 18,  0,  0,  0]])

In [105]:
# for embedding in keras word vectorization should be integer encoded
from keras.layers import Embedding
from keras import Sequential
model = Sequential()
# vocabulary = 17, output vector will be of dim 2, each input has 5 words
# model.add(Embedding(input_dim=18, output_dim=2, input_length=5)) # this layer is not required in integer encoding only, here cbow or skip-grams is happing?/ here embedding layer is also getting trained/ how embedding layer is working in keras
model.add(Embedding(input_dim=19, output_dim=2, input_shape=(5,)))
# one review is going at once, each review is going by 17 dim vector
model.summary()

Model: "sequential_11"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_11 (Embedding)             │ (None, 5, 2)                │              38 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 38 (152.00 B)

 Trainable params: 38 (152.00 B)

 Non-trainable params: 0 (0.00 B)

In [107]:
model.compile('adam', 'accuracy')
# model.fit

In [109]:
pred = model.predict(sequences) # without training also we can see predictions of words which will be initial allocation of numbers in vectors, if we do training (fit) then those numbers will be updated by backpropagation
pred

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step


array([[[-0.00010861, -0.01319213],
        [ 0.03843273,  0.04144422],
        [-0.02566025, -0.02050959],
        [-0.02566025, -0.02050959],
        [-0.02566025, -0.02050959]],

       [[ 0.03843273,  0.04144422],
        [ 0.03843273,  0.04144422],
        [-0.02566025, -0.02050959],
        [-0.02566025, -0.02050959],
        [-0.02566025, -0.02050959]],

       [[-0.0168651 ,  0.0138579 ],
        [-0.0168651 ,  0.0138579 ],
        [-0.04515381, -0.04491419],
        [-0.02566025, -0.02050959],
        [-0.02566025, -0.02050959]],

       [[ 0.01257409,  0.03568036],
        [-0.02115488, -0.02106913],
        [ 0.01257409,  0.03568036],
        [ 0.03843273,  0.04144422],
        [ 0.01257409,  0.03568036]],

       [[ 0.02930666, -0.03103534],
        [ 0.03307099,  0.03756152],
        [-0.04772133,  0.0068895 ],
        [ 0.00756856,  0.00792011],
        [-0.02566025, -0.02050959]],

       [[-0.04465233, -0.02108065],
        [-0.04465233, -0.02108065],
        [-0.025660

In [ ]:
# only training embeddings for classification
from keras.models import Sequential
from keras.layers import Embedding, GlobalAveragePooling1D, Dense

model = Sequential([
    Embedding(input_dim=10000, output_dim=32, input_length=100),   # Learn embeddings
    GlobalAveragePooling1D(),                                      # Aggregate word embeddings
    Dense(1, activation='sigmoid')                                 # Binary classification
])

# Freeze everything except embedding layer (if you want)
model.layers[2].trainable = False  # Freeze Dense if needed

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=5, batch_size=32)

# Get the trained embedding weights
embedding_matrix = model.layers[0].get_weights()[0]

# Why GlobalAveragePooling1D()?
# Since you’re removing the SimpleRNN, you need a way to reduce the sequence of embeddings into a single vector per sample.

# or have to train embedding together with RNN layer as done in imdb example

# Use Only the Embedding Layer for Unsupervised Pretraining
# If your goal is just to train embeddings, and not for classification, you might consider:

# Using Word2Vec or GloVe (unsupervised)

# Or supervised tasks like classification (as we did) or next-word prediction


In [51]:
# imdb - movie review dataset
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense, SimpleRNN, Embedding, Flatten

In [53]:
(X_train, y_train), (X_test, y_test) = imdb.load_data()

In [54]:
X_train.shape

(25000,)

In [55]:
X_test.shape

(25000,)

In [56]:
X_train # data already preprocessed - integer encoded

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1

In [57]:
X_train[0]

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 22665,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 21631,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 19193,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 10311,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 31050,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 12118,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5

In [58]:
print(len(X_train[0]), len(X_train[1]), len(X_train[2]), len(X_train[3]))

218 189 141 550


In [59]:
# as input length is different, usual behaviour , doing padding
# trimming all reviews to 50 to reduce training time, loosing rest input words
# we can train including all words, remove maxlen = 50
X_train = pad_sequences(X_train, padding='post', maxlen = 50)
X_test = pad_sequences(X_test, padding='post', maxlen = 50)

In [60]:
X_train[0]

array([2071,   56,   26,  141,    6,  194, 7486,   18,    4,  226,   22,
         21,  134,  476,   26,  480,    5,  144,   30, 5535,   18,   51,
         36,   28,  224,   92,   25,  104,    4,  226,   65,   16,   38,
       1334,   88,   12,   16,  283,    5,   16, 4472,  113,  103,   32,
         15,   16, 5345,   19,  178,   32])

In [61]:
model = Sequential()
model.add(Embedding(input_dim=10000, output_dim=2, input_shape = (50,)))
model.add(SimpleRNN(32, return_sequences=False)) # here input_shape ? is it 2 as we are representing each word as embedding of 2 numbers, though it's not reqd to mention here, for understanding asking
# for sentiment analysis intermediate o/p is not reqd, so return_sequences=False, for NER, machine trans, it will be True bcz int output will be reqd there
# model.add(SimpleRNN(32, input_shape=(50,1), return_sequences=False)) # 50 timesteps as we have trimmed input size to 50, it will be maxlength of inputs, 1 feature is there so second term is 1
model.add(Dense(1,activation='sigmoid'))
model.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_8 (Embedding)              │ (None, 50, 2)               │          20,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn_4 (SimpleRNN)             │ (None, 32)                  │           1,120 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 21,153 (82.63 KB)

 Trainable params: 21,153 (82.63 KB)

 Non-trainable params: 0 (0.00 B)

In [71]:
model.compile(loss='binary_crossentropy', optimizer = 'adam', metrics = ['acc'])
model.fit(X_train, y_train, epochs=5, validation_data = (X_test, y_test))

Epoch 1/5


InvalidArgumentError: Graph execution error:

Detected at node sequential_8_1/embedding_8_1/GatherV2 defined at (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "C:\Users\koyel\anaconda3\Lib\site-packages\ipykernel_launcher.py", line 17, in <module>

  File "C:\Users\koyel\anaconda3\Lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance

  File "C:\Users\koyel\anaconda3\Lib\site-packages\ipykernel\kernelapp.py", line 701, in start

  File "C:\Users\koyel\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start

  File "C:\Users\koyel\anaconda3\Lib\asyncio\windows_events.py", line 322, in run_forever

  File "C:\Users\koyel\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever

  File "C:\Users\koyel\anaconda3\Lib\asyncio\base_events.py", line 1987, in _run_once

  File "C:\Users\koyel\anaconda3\Lib\asyncio\events.py", line 88, in _run

  File "C:\Users\koyel\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue

  File "C:\Users\koyel\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one

  File "C:\Users\koyel\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell

  File "C:\Users\koyel\anaconda3\Lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request

  File "C:\Users\koyel\anaconda3\Lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute

  File "C:\Users\koyel\anaconda3\Lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell

  File "C:\Users\koyel\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3075, in run_cell

  File "C:\Users\koyel\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3130, in _run_cell

  File "C:\Users\koyel\anaconda3\Lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner

  File "C:\Users\koyel\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3334, in run_cell_async

  File "C:\Users\koyel\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3517, in run_ast_nodes

  File "C:\Users\koyel\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py", line 3577, in run_code

  File "C:\Users\koyel\AppData\Local\Temp\ipykernel_15540\2045095954.py", line 2, in <module>

  File "C:\Users\koyel\anaconda3\Lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "C:\Users\koyel\anaconda3\Lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 320, in fit

  File "C:\Users\koyel\anaconda3\Lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 121, in one_step_on_iterator

  File "C:\Users\koyel\anaconda3\Lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 108, in one_step_on_data

  File "C:\Users\koyel\anaconda3\Lib\site-packages\keras\src\backend\tensorflow\trainer.py", line 51, in train_step

  File "C:\Users\koyel\anaconda3\Lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "C:\Users\koyel\anaconda3\Lib\site-packages\keras\src\layers\layer.py", line 899, in __call__

  File "C:\Users\koyel\anaconda3\Lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "C:\Users\koyel\anaconda3\Lib\site-packages\keras\src\ops\operation.py", line 46, in __call__

  File "C:\Users\koyel\anaconda3\Lib\site-packages\keras\src\utils\traceback_utils.py", line 156, in error_handler

  File "C:\Users\koyel\anaconda3\Lib\site-packages\keras\src\models\sequential.py", line 213, in call

  File "C:\Users\koyel\anaconda3\Lib\site-packages\keras\src\models\functional.py", line 182, in call

  File "C:\Users\koyel\anaconda3\Lib\site-packages\keras\src\ops\function.py", line 171, in _run_through_graph

  File "C:\Users\koyel\anaconda3\Lib\site-packages\keras\src\models\functional.py", line 584, in call

  File "C:\Users\koyel\anaconda3\Lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "C:\Users\koyel\anaconda3\Lib\site-packages\keras\src\layers\layer.py", line 899, in __call__

  File "C:\Users\koyel\anaconda3\Lib\site-packages\keras\src\utils\traceback_utils.py", line 117, in error_handler

  File "C:\Users\koyel\anaconda3\Lib\site-packages\keras\src\ops\operation.py", line 46, in __call__

  File "C:\Users\koyel\anaconda3\Lib\site-packages\keras\src\utils\traceback_utils.py", line 156, in error_handler

  File "C:\Users\koyel\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py", line 140, in call

  File "C:\Users\koyel\anaconda3\Lib\site-packages\keras\src\ops\numpy.py", line 5206, in take

  File "C:\Users\koyel\anaconda3\Lib\site-packages\keras\src\backend\tensorflow\numpy.py", line 2029, in take

indices[0,16] = 10500 is not in [0, 10000)
	 [[{{node sequential_8_1/embedding_8_1/GatherV2}}]] [Op:__inference_one_step_on_iterator_2327]

# Next Word Predictor Using LSTM

In [80]:
faqs = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.campusx@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
"""

In [ ]:
# we are building a text generator
# supervised learning problem

In [84]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [86]:
tokenizer = Tokenizer()

In [88]:
tokenizer.fit_on_texts([faqs])

In [90]:
tokenizer.word_index

{'the': 1,
 'you': 2,
 'i': 3,
 'to': 4,
 'a': 5,
 'of': 6,
 'is': 7,
 'have': 8,
 'will': 9,
 'can': 10,
 'what': 11,
 'course': 12,
 'program': 13,
 'in': 14,
 'for': 15,
 'all': 16,
 'sessions': 17,
 'on': 18,
 'be': 19,
 'and': 20,
 'this': 21,
 'if': 22,
 'am': 23,
 'pay': 24,
 'payment': 25,
 'make': 26,
 'we': 27,
 'do': 28,
 'subscription': 29,
 'where': 30,
 'rs': 31,
 'so': 32,
 'campusx': 33,
 'session': 34,
 'our': 35,
 'paid': 36,
 'join': 37,
 'able': 38,
 'your': 39,
 'website': 40,
 'placement': 41,
 'fee': 42,
 'data': 43,
 'monthly': 44,
 'month': 45,
 'not': 46,
 'get': 47,
 'yes': 48,
 'once': 49,
 'past': 50,
 'feb': 51,
 'assistance': 52,
 'science': 53,
 '7': 54,
 '5600': 55,
 'are': 56,
 'watch': 57,
 'google': 58,
 'by': 59,
 'com': 60,
 'mail': 61,
 'from': 62,
 'contact': 63,
 'us': 64,
 'at': 65,
 'or': 66,
 'doubt': 67,
 'mentorship': 68,
 'payments': 69,
 '799': 70,
 'total': 71,
 'duration': 72,
 'months': 73,
 'learning': 74,
 'case': 75,
 'here': 76,
 '

In [92]:
for sentence in faqs.split('\n'):
    print(sentence)

About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a sessi

In [104]:
for sentence in faqs.split('\n'):
    print(tokenizer.texts_to_sequences([sentence])[0])

[93, 1, 13]
[11, 7, 1, 12, 42, 15, 43, 53, 68, 13, 147, 148]
[1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44, 69, 6, 31, 70, 45]
[11, 7, 1, 71, 72, 6, 1, 12]
[1, 71, 72, 6, 1, 12, 7, 54, 73, 32, 1, 71, 12, 42, 149, 70, 54, 31, 55, 150]
[11, 7, 1, 96, 6, 1, 68, 13]
[27, 9, 19, 151, 1, 152, 153]
[97, 154]
[97, 155, 15, 43, 53]
[43, 156]
[157, 15, 43, 53]
[158, 15, 159, 74]
[98, 160]
[161, 98]
[162]
[75, 99]
[2, 10, 163, 1, 164, 96, 76, 77, 100, 33, 14, 165, 33, 43, 53, 68, 13, 166]
[9, 101, 74, 20, 102, 19, 5, 78, 6, 21, 13]
[103, 102, 20, 101, 74, 167, 56, 46, 5, 78, 6, 21, 168, 169]
[11, 22, 3, 104, 5, 105, 34, 9, 3, 47, 5, 106, 6, 1, 34]
[48, 16, 35, 17, 56, 170, 32, 107, 22, 2, 104, 5, 34, 2, 10, 171, 172, 20, 57, 1, 106]
[30, 10, 3, 173, 1, 108, 174]
[175, 21, 58, 176, 4, 79, 45, 59, 45, 109, 177, 6, 1, 12, 77, 178, 58, 60, 179, 180, 181, 182, 183, 184, 185]
[11, 7, 1, 109, 72, 6, 16, 1, 105, 17]
[186, 16, 1, 17, 187, 110, 188]
[11, 7, 1, 189, 190, 59, 1, 191, 192, 1, 17]
[193]
[111,

In [108]:
input_sequences = []
for sentence in faqs.split('\n'):
    tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]
    for i in range(1, len(tokenized_sentence)):
        input_sequences.append(tokenized_sentence[:i+1])

In [110]:
input_sequences

[[93, 1],
 [93, 1, 13],
 [11, 7],
 [11, 7, 1],
 [11, 7, 1, 12],
 [11, 7, 1, 12, 42],
 [11, 7, 1, 12, 42, 15],
 [11, 7, 1, 12, 42, 15, 43],
 [11, 7, 1, 12, 42, 15, 43, 53],
 [11, 7, 1, 12, 42, 15, 43, 53, 68],
 [11, 7, 1, 12, 42, 15, 43, 53, 68, 13],
 [11, 7, 1, 12, 42, 15, 43, 53, 68, 13, 147],
 [11, 7, 1, 12, 42, 15, 43, 53, 68, 13, 147, 148],
 [1, 12],
 [1, 12, 94],
 [1, 12, 94, 5],
 [1, 12, 94, 5, 44],
 [1, 12, 94, 5, 44, 29],
 [1, 12, 94, 5, 44, 29, 95],
 [1, 12, 94, 5, 44, 29, 95, 30],
 [1, 12, 94, 5, 44, 29, 95, 30, 2],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44, 69],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44, 69, 6],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44, 69, 6, 31],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44, 69, 6, 31, 70],
 [1, 12, 94, 5, 44, 29, 95, 30, 2, 8, 4, 26, 44, 69, 6

In [114]:
max_len = max([len(x) for x in input_sequences])
max_len

57

In [116]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
pad_sequences(input_sequences, maxlen = max_len, padding='pre')

array([[  0,   0,   0, ...,   0,  93,   1],
       [  0,   0,   0, ...,  93,   1,  13],
       [  0,   0,   0, ...,   0,  11,   7],
       ...,
       [  0,   0,   0, ..., 279,  18, 280],
       [  0,   0,   0, ...,  18, 280, 281],
       [  0,   0,   0, ..., 280, 281, 282]])

In [118]:
padded_input_sequences = pad_sequences(input_sequences, maxlen = max_len, padding='pre')
padded_input_sequences

array([[  0,   0,   0, ...,   0,  93,   1],
       [  0,   0,   0, ...,  93,   1,  13],
       [  0,   0,   0, ...,   0,  11,   7],
       ...,
       [  0,   0,   0, ..., 279,  18, 280],
       [  0,   0,   0, ...,  18, 280, 281],
       [  0,   0,   0, ..., 280, 281, 282]])

In [120]:
padded_input_sequences[:,:-1]

array([[  0,   0,   0, ...,   0,   0,  93],
       [  0,   0,   0, ...,   0,  93,   1],
       [  0,   0,   0, ...,   0,   0,  11],
       ...,
       [  0,   0,   0, ...,   0, 279,  18],
       [  0,   0,   0, ..., 279,  18, 280],
       [  0,   0,   0, ...,  18, 280, 281]])

In [122]:
padded_input_sequences[:,-1]

array([  1,  13,   7,   1,  12,  42,  15,  43,  53,  68,  13, 147, 148,
        12,  94,   5,  44,  29,  95,  30,   2,   8,   4,  26,  44,  69,
         6,  31,  70,  45,   7,   1,  71,  72,   6,   1,  12,  71,  72,
         6,   1,  12,   7,  54,  73,  32,   1,  71,  12,  42, 149,  70,
        54,  31,  55, 150,   7,   1,  96,   6,   1,  68,  13,   9,  19,
       151,   1, 152, 153, 154, 155,  15,  43,  53, 156,  15,  43,  53,
        15, 159,  74, 160,  98,  99,  10, 163,   1, 164,  96,  76,  77,
       100,  33,  14, 165,  33,  43,  53,  68,  13, 166, 101,  74,  20,
       102,  19,   5,  78,   6,  21,  13, 102,  20, 101,  74, 167,  56,
        46,   5,  78,   6,  21, 168, 169,  22,   3, 104,   5, 105,  34,
         9,   3,  47,   5, 106,   6,   1,  34,  16,  35,  17,  56, 170,
        32, 107,  22,   2, 104,   5,  34,   2,  10, 171, 172,  20,  57,
         1, 106,  10,   3, 173,   1, 108, 174,  21,  58, 176,   4,  79,
        45,  59,  45, 109, 177,   6,   1,  12,  77, 178,  58,  6

In [144]:
X = padded_input_sequences[:,:-1]
y = padded_input_sequences[:,-1]

In [ ]:
# use this problem as multiclass classification problem
# do ohe for output class

In [126]:
X.shape

(863, 56)

In [128]:
y.shape

(863,)

In [136]:
tokenizer.word_index

{'the': 1,
 'you': 2,
 'i': 3,
 'to': 4,
 'a': 5,
 'of': 6,
 'is': 7,
 'have': 8,
 'will': 9,
 'can': 10,
 'what': 11,
 'course': 12,
 'program': 13,
 'in': 14,
 'for': 15,
 'all': 16,
 'sessions': 17,
 'on': 18,
 'be': 19,
 'and': 20,
 'this': 21,
 'if': 22,
 'am': 23,
 'pay': 24,
 'payment': 25,
 'make': 26,
 'we': 27,
 'do': 28,
 'subscription': 29,
 'where': 30,
 'rs': 31,
 'so': 32,
 'campusx': 33,
 'session': 34,
 'our': 35,
 'paid': 36,
 'join': 37,
 'able': 38,
 'your': 39,
 'website': 40,
 'placement': 41,
 'fee': 42,
 'data': 43,
 'monthly': 44,
 'month': 45,
 'not': 46,
 'get': 47,
 'yes': 48,
 'once': 49,
 'past': 50,
 'feb': 51,
 'assistance': 52,
 'science': 53,
 '7': 54,
 '5600': 55,
 'are': 56,
 'watch': 57,
 'google': 58,
 'by': 59,
 'com': 60,
 'mail': 61,
 'from': 62,
 'contact': 63,
 'us': 64,
 'at': 65,
 'or': 66,
 'doubt': 67,
 'mentorship': 68,
 'payments': 69,
 '799': 70,
 'total': 71,
 'duration': 72,
 'months': 73,
 'learning': 74,
 'case': 75,
 'here': 76,
 '

In [132]:
len(tokenizer.word_index)

282

In [134]:
# ohe y
from tensorflow.keras.utils import to_categorical
to_categorical(y, num_classes = 283)

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [146]:
y = to_categorical(y, num_classes = 283)
y

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [148]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [194]:
model = Sequential()
model.add(Embedding(283, 100, input_length = 56)) # creating dense vector from padded sparse inputs
model.add(LSTM(150)) # number of nodes in LSTM layers
model.add(Dense(283, activation = 'softmax'))

In [196]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [198]:
model.fit(X, y, epochs=5)

Epoch 1/5
27/27 ━━━━━━━━━━━━━━━━━━━━ 7s 66ms/step - accuracy: 0.0524 - loss: 5.5477
Epoch 2/5
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 68ms/step - accuracy: 0.0677 - loss: 5.0837
Epoch 3/5
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 65ms/step - accuracy: 0.0669 - loss: 4.9975
Epoch 4/5
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 65ms/step - accuracy: 0.0731 - loss: 4.9730
Epoch 5/5
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 65ms/step - accuracy: 0.0700 - loss: 4.9378


In [199]:
text = 'payment' #'text'

# tokenize
token_text = tokenizer.texts_to_sequences([text])[0]
# padding
padded_token_text = pad_sequences([token_text], maxlen=56, padding = 'pre')
print(padded_token_text)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0 25]]


In [185]:
# predict
model.predict(padded_token_text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step


array([[4.69495499e-05, 1.02223523e-01, 2.18688045e-02, 2.97171120e-02,
        3.97249386e-02, 2.24257857e-02, 2.23091915e-02, 3.07820886e-02,
        2.32969169e-02, 1.66498274e-02, 2.47348398e-02, 4.23424412e-03,
        1.41200935e-02, 1.54672014e-02, 1.19290464e-02, 1.21287601e-02,
        1.55368205e-02, 8.81091226e-03, 9.76413675e-03, 8.78306571e-03,
        1.22632394e-02, 7.58889457e-03, 8.58241506e-03, 9.33368690e-03,
        8.74683354e-03, 6.09806785e-03, 8.05834308e-03, 9.53463931e-03,
        1.01218680e-02, 6.37054583e-03, 1.50101574e-03, 6.58427412e-03,
        7.64226168e-03, 5.55531448e-03, 5.35267545e-03, 6.77889539e-03,
        5.70141757e-03, 6.66508405e-03, 4.22768202e-03, 5.81712509e-03,
        5.88588323e-03, 6.68910658e-03, 5.95088862e-03, 3.99029721e-03,
        4.86323703e-03, 4.98764683e-03, 5.24516730e-03, 6.69009378e-03,
        1.22260783e-04, 5.45114838e-03, 5.51171508e-03, 4.68858937e-03,
        5.54425968e-03, 4.19107452e-03, 3.60842724e-03, 4.491136

In [202]:
model.predict(padded_token_text).shape

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 411ms/step


(1, 283)

In [204]:
import numpy as np
np.argmax(model.predict(padded_token_text))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step


1

In [206]:
pos = np.argmax(model.predict(padded_token_text))
for word, index in tokenizer.word_index.items():
    if index == pos:
        print(word)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
the


In [172]:
text = 'text'

for i in range(5):
    # tokenize
    token_text = tokenizer.texts_to_sequences([text])[0]
    # padding
    padded_token_text = pad_sequences([token_text], maxlen=56, padding = 'pre')
    pos = np.argmax(model.predict(padded_token_text))
    for word, index in tokenizer.word_index.items():
        if index == pos:
            text = text + " " + word
            print(text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
text the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
text the the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
text the the the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
text the the the the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
text the the the the the


# Deep/Stacked RNN

In [2]:
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

In [6]:
# Load the IMDB dataset
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words = 10000)

# pad sequences to have the same length
x_train = pad_sequences(x_train, maxlen=100)
x_test = pad_sequences(x_test, maxlen=100)

In [10]:
# Define the RNN Model
model = Sequential([
    Embedding(10000, 32, input_length = 100), # Embedding layer to convert words to vectors
    SimpleRNN(5, return_sequences=True), # RNN layer with 5 units
    SimpleRNN(5),                        # another RNN layer with 5 units
    Dense(1, activation='sigmoid')       # output layer for binaru classification
])
# GRU/LSTM layer in place of SimpleRNN to get deep LsTM and deep GRU
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn_1 (SimpleRNN)             │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn_2 (SimpleRNN)             │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(optimizer = 'adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
history = model.fit(x_train, y_train, epochs=5, batch_size=32, validation_split=0.2)

# Bidirectional RNN

In [ ]:
# Define the RNN Model
model = Sequential([
    Embedding(10000, 32, input_length = 100), # Embedding layer to convert words to vectors
    Bidirectional(SimpleRNN(5, return_sequences=True)), # RNN layer with 5 units for bidirectional
    Dense(1, activation='sigmoid')       # output layer for binaru classification
])
# GRU/LSTM layer in place of SimpleRNN to get bidirectional LsTM and bidirectional GRU
model.summary()

In [ ]:
model.summary()

In [ ]:
model.compile(optimizer = 'adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
history = model.fit(x_train, y_train, epochs=5, batch_size=32, validation_split=0.2)

Can we use bidirectional deep RNN/LSTM/GRU?